---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: myns
  labels:
    volume-name: my-pv
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: vol001
  persistentVolumeReclaimPolicy: Retain
