---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata: 
  name: myapp-hpa
  namespace: myns
  labels:
    name: myapp-hpa

spec:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
