---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: myns
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"