---
kind: Deployment
apiVersion: apps/v1

metadata: 
  name: myapp-deployment
  namespace: myns
  labels: 
    app: myapp-deploy
  
spec: 
  replicas: 4
  selector: 
    matchLabels: 
      app: myapp-pod
  template: 
    metadata: 
      name: myapp-pod
      namespace: myns
      labels: 
        app: myapp-pod
        version: v2
    spec: 
      containers:
        - name: myapp
          image: stackupiss/northwind-app:v2
          imagePullPolicy: Always
          env: 
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef: 
                name: myapp-config
                key: db_host
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: myapp-secret
                key: db_password
          - name: INSTANCE_IP_ADDRESS
            valueFrom: 
              fieldRef: 
                fieldPath: status.podIP
          ports: 
          - name: myapp-port
            containerPort: 3000

---
kind: Service
apiVersion: v1

metadata: 
  name: myapp-svc
  namespace: myns
  labels:
    app: myapp-svc

spec:
  type: LoadBalancer
  selector: 
    app: myapp-pod
  ports:
    - name: myapp-svc-port
      port: 80
      targetPort: myapp-port